// ternary-rom cell library: sky130
// Generated by ROMCellLibrary
// SkyWater 130nm open-source process

module ROM_PLUS_X1 (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_MINUS_X1 (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_ZERO_X1 (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule
