// ternary-rom cell library: samsung14_lpp
// Generated by ROMCellLibrary
// Samsung 14nm LPP FinFET
// Cells: 29

module ROM_PLUS_X1_hvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X1, Vt: hvt
  // Size: 0.09 x 0.09 um, Leakage: 0.105 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X1_lvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X1, Vt: lvt
  // Size: 0.09 x 0.09 um, Leakage: 2.1 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X1 (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X1, Vt: std
  // Size: 0.09 x 0.09 um, Leakage: 0.7 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X2_hvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X2, Vt: hvt
  // Size: 0.18 x 0.09 um, Leakage: 0.21 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X2_lvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X2, Vt: lvt
  // Size: 0.18 x 0.09 um, Leakage: 4.2 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X2 (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X2, Vt: std
  // Size: 0.18 x 0.09 um, Leakage: 1.4 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X4_hvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X4, Vt: hvt
  // Size: 0.36 x 0.09 um, Leakage: 0.42 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X4_lvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X4, Vt: lvt
  // Size: 0.36 x 0.09 um, Leakage: 8.4 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X4 (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X4, Vt: std
  // Size: 0.36 x 0.09 um, Leakage: 2.8 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_MINUS_X1_hvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X1, Vt: hvt
  // Size: 0.09 x 0.09 um, Leakage: 0.105 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X1_lvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X1, Vt: lvt
  // Size: 0.09 x 0.09 um, Leakage: 2.1 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X1 (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X1, Vt: std
  // Size: 0.09 x 0.09 um, Leakage: 0.7 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X2_hvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X2, Vt: hvt
  // Size: 0.18 x 0.09 um, Leakage: 0.21 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X2_lvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X2, Vt: lvt
  // Size: 0.18 x 0.09 um, Leakage: 4.2 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X2 (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X2, Vt: std
  // Size: 0.18 x 0.09 um, Leakage: 1.4 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X4_hvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X4, Vt: hvt
  // Size: 0.36 x 0.09 um, Leakage: 0.42 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X4_lvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X4, Vt: lvt
  // Size: 0.36 x 0.09 um, Leakage: 8.4 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X4 (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X4, Vt: std
  // Size: 0.36 x 0.09 um, Leakage: 2.8 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_ZERO_X1_hvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X1, Vt: hvt
  // Size: 0.09 x 0.09 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X1_lvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X1, Vt: lvt
  // Size: 0.09 x 0.09 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X1 (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X1, Vt: std
  // Size: 0.09 x 0.09 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X2_hvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X2, Vt: hvt
  // Size: 0.18 x 0.09 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X2_lvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X2, Vt: lvt
  // Size: 0.18 x 0.09 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X2 (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X2, Vt: std
  // Size: 0.18 x 0.09 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X4_hvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X4, Vt: hvt
  // Size: 0.36 x 0.09 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X4_lvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X4, Vt: lvt
  // Size: 0.36 x 0.09 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X4 (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X4, Vt: std
  // Size: 0.36 x 0.09 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_REF_HI (WL, BL);
  // ROM_REF_HI: always drives BL to VDD (reference high)
  // Drive: X1, Vt: std
  // Size: 0.09 x 0.09 um, Leakage: 0.7 pA
  input WL;
  output BL;

  assign BL = 1'b1;

endmodule

module ROM_REF_LO (WL, BL);
  // ROM_REF_LO: always drives BL to VSS (reference low)
  // Drive: X1, Vt: std
  // Size: 0.09 x 0.09 um, Leakage: 0.7 pA
  input WL;
  output BL;

  assign BL = 1'b0;

endmodule
