import type { Discovery } from './types';

export const allDiscoveries: Discovery[] = [
  // ── Farm (Pattern Recognition & Classification) ──────────────────
  {
    id: 'sheep-sight',
    name: 'First Sheep Sighting',
    emoji: '🐑',
    aiConcept: 'Pattern Recognition',
    xp: 10,
    world: 'farm',
  },
  {
    id: 'flock-mind',
    name: 'Flock Mind',
    emoji: '🧠',
    aiConcept: 'Clustering',
    xp: 15,
    world: 'farm',
    hint: 'Watch how the sheep stick together...',
  },
  {
    id: 'pen-purpose',
    name: 'The Gathering Place',
    emoji: '🏡',
    aiConcept: 'Classification',
    xp: 10,
    world: 'farm',
  },
  {
    id: 'elder-home',
    name: "Elder's Kennel",
    emoji: '🏠',
    aiConcept: 'Knowledge Distillation',
    xp: 10,
    world: 'farm',
  },
  {
    id: 'grass-pattern',
    name: 'Grass Pattern',
    emoji: '🌿',
    aiConcept: 'Feature Detection',
    xp: 5,
    world: 'farm',
  },
  {
    id: 'hay-bale-sort',
    name: 'Hay Bale Sort',
    emoji: '📜',
    aiConcept: 'Decision Boundaries',
    xp: 15,
    world: 'farm',
    hint: 'The hay bales seem to be sorted somehow...',
  },
  {
    id: 'wool-color-match',
    name: 'Wool Color Match',
    emoji: '🧳',
    aiConcept: 'Supervised Classification',
    xp: 20,
    world: 'farm',
    hidden: true,
  },
  {
    id: 'sheep-herd-instinct',
    name: 'Herd Instinct',
    emoji: '🐕',
    aiConcept: 'Unsupervised Clustering',
    xp: 20,
    world: 'farm',
    hidden: true,
  },

  // ── Forest (Search Algorithms & Optimization) ───────────────────
  {
    id: 'forest-path',
    name: 'Hidden Path',
    emoji: '🌲',
    aiConcept: 'Search',
    xp: 15,
    world: 'forest',
    hint: 'Not every path is visible from the start.',
  },
  {
    id: 'stream-cross',
    name: 'Bridge Crossed',
    emoji: '🌊',
    aiConcept: 'Graph Optimization',
    xp: 10,
    world: 'forest',
  },
  {
    id: 'mushroom-ring',
    name: 'Mushroom Ring',
    emoji: '🍄',
    aiConcept: 'Pattern Recognition',
    xp: 15,
    world: 'forest',
  },
  {
    id: 'cave-dark',
    name: 'Dark Cave',
    emoji: '🦇',
    aiConcept: 'Exploration',
    xp: 20,
    world: 'forest',
    hidden: true,
  },
  {
    id: 'firefly-glow',
    name: 'Firefly Glow',
    emoji: '✨',
    aiConcept: 'Signal Processing',
    xp: 10,
    world: 'forest',
  },
  {
    id: 'owl-direction',
    name: "Owl's Direction",
    emoji: '🦉',
    aiConcept: 'Heuristic Guidance',
    xp: 15,
    world: 'forest',
    hint: 'The owl always seems to know the way...',
  },
  {
    id: 'trail-marking',
    name: 'Trail Marking',
    emoji: '📖',
    aiConcept: 'Search Memoization',
    xp: 10,
    world: 'forest',
  },
  {
    id: 'ancient-oak',
    name: 'Ancient Oak',
    emoji: '🌳',
    aiConcept: 'Local Optima',
    xp: 25,
    world: 'forest',
    hidden: true,
  },

  // ── Village (Neural Networks & Weights) ─────────────────────────
  {
    id: 'house-link',
    name: 'Connected Houses',
    emoji: '🏘️',
    aiConcept: 'Neural Connections',
    xp: 15,
    world: 'village',
  },
  {
    id: 'fountain-center',
    name: 'Central Hub',
    emoji: '⛲',
    aiConcept: 'Network Layers',
    xp: 15,
    world: 'village',
    hint: 'All paths lead to the fountain eventually.',
  },
  {
    id: 'crossroads',
    name: 'Busy Intersection',
    emoji: '🛤️',
    aiConcept: 'Feature Aggregation',
    xp: 10,
    world: 'village',
  },
  {
    id: 'market-square',
    name: 'Market Square',
    emoji: '🎬',
    aiConcept: 'Data Processing',
    xp: 10,
    world: 'village',
  },
  {
    id: 'bell-tower',
    name: 'Bell Tower',
    emoji: '🔔',
    aiConcept: 'Signal Propagation',
    xp: 20,
    world: 'village',
  },
  {
    id: 'rooftop-antenna',
    name: 'Rooftop Antenna',
    emoji: '🛡️',
    aiConcept: 'Weight Initialization',
    xp: 15,
    world: 'village',
    hint: 'The antenna catches signals from far away.',
  },
  {
    id: 'sewer-gate',
    name: 'Sewer Gate',
    emoji: '💧',
    aiConcept: 'Activation Function',
    xp: 20,
    world: 'village',
    hidden: true,
  },
  {
    id: 'windmill-gears',
    name: 'Windmill Gears',
    emoji: '🌲',
    aiConcept: 'Backpropagation',
    xp: 25,
    world: 'village',
    hidden: true,
  },

  // ── Mountain (Model Training & Generalization) ──────────────────
  {
    id: 'crystal-glow',
    name: 'Data Crystal',
    emoji: '💎',
    aiConcept: 'Model Weights',
    xp: 20,
    world: 'mountain',
  },
  {
    id: 'campfire-warm',
    name: 'Training Fire',
    emoji: '🔥',
    aiConcept: 'Training Loop',
    xp: 15,
    world: 'mountain',
    hint: 'The fire grows stronger with each log added.',
  },
  {
    id: 'summit-view',
    name: 'Summit Reached',
    emoji: '🗻️',
    aiConcept: 'Generalization',
    xp: 30,
    world: 'mountain',
  },
  {
    id: 'eagle-perspective',
    name: "Eagle's View",
    emoji: '🦅',
    aiConcept: 'Emergent Understanding',
    xp: 25,
    world: 'mountain',
  },
  {
    id: 'snow-flake',
    name: 'Unique Snowflake',
    emoji: '❄️',
    aiConcept: 'Individual Data Points',
    xp: 10,
    world: 'mountain',
  },
  {
    id: 'avalanche-echo',
    name: 'Avalanche Echo',
    emoji: '🌪️',
    aiConcept: 'Gradient Descent',
    xp: 25,
    world: 'mountain',
    hint: 'The smallest pebble can start the biggest slide.',
  },
  {
    id: 'icicle-shape',
    name: 'Icicle Shape',
    emoji: '🌨️',
    aiConcept: 'Overfitting',
    xp: 20,
    world: 'mountain',
    hidden: true,
  },
  {
    id: 'base-camp-journal',
    name: 'Base Camp Journal',
    emoji: '📓',
    aiConcept: 'Training History',
    xp: 15,
    world: 'mountain',
  },

  // ── Meadow (Reinforcement Learning) ─────────────────────────────
  {
    id: 'reward-signal',
    name: 'Reward Signal',
    emoji: '🌟',
    aiConcept: 'Reward Function',
    xp: 10,
    world: 'meadow',
    hint: 'Every good action earns a little sparkle.',
  },
  {
    id: 'explore-exploit',
    name: 'Explore or Exploit',
    emoji: '🔍',
    aiConcept: 'Exploration vs. Exploitation',
    xp: 20,
    world: 'meadow',
  },
  {
    id: 'policy-path',
    name: 'Policy Path',
    emoji: '🚩',
    aiConcept: 'Policy',
    xp: 15,
    world: 'meadow',
    hint: 'The wisest pup follows a plan, not just instinct.',
  },
  {
    id: 'q-value-crystal',
    name: 'Q-Value Crystal',
    emoji: '💎',
    aiConcept: 'Q-Learning',
    xp: 25,
    world: 'meadow',
    hidden: true,
  },
  {
    id: 'reward-shape',
    name: 'Reward Shaping',
    emoji: '🌸',
    aiConcept: 'Reward Shaping',
    xp: 20,
    world: 'meadow',
  },
  {
    id: 'optimal-route',
    name: 'Optimal Route',
    emoji: '📱',
    aiConcept: 'Optimal Policy',
    xp: 25,
    world: 'meadow',
  },
  {
    id: 'delayed-reward',
    name: 'Delayed Reward',
    emoji: '⏳',
    aiConcept: 'Delayed Rewards',
    xp: 30,
    world: 'meadow',
    hidden: true,
  },

  // ── Lake (Data Processing & Pipelines) ──────────────────────────
  {
    id: 'stream-source',
    name: 'Stream Source',
    emoji: '💧',
    aiConcept: 'Data Source',
    xp: 10,
    world: 'lake',
    hint: 'Every stream starts from somewhere small.',
  },
  {
    id: 'filter-net',
    name: 'Filter Net',
    emoji: '🦣',
    aiConcept: 'Data Filtering',
    xp: 15,
    world: 'lake',
  },
  {
    id: 'batch-stone',
    name: 'Batch Stone',
    emoji: '🪨',
    aiConcept: 'Batching',
    xp: 15,
    world: 'lake',
    hint: 'Skip stones work best in groups of three.',
  },
  {
    id: 'augment-flower',
    name: 'Augment Flower',
    emoji: '🌼',
    aiConcept: 'Data Augmentation',
    xp: 20,
    world: 'lake',
  },
  {
    id: 'normalize-pool',
    name: 'Normalize Pool',
    emoji: '🏊',
    aiConcept: 'Normalization',
    xp: 20,
    world: 'lake',
    hidden: true,
  },
  {
    id: 'clean-water',
    name: 'Clean Water',
    emoji: '💧',
    aiConcept: 'Data Cleaning',
    xp: 15,
    world: 'lake',
  },
  {
    id: 'pipeline-end',
    name: 'Pipeline End',
    emoji: '📦',
    aiConcept: 'Data Pipeline',
    xp: 25,
    world: 'lake',
    hidden: true,
  },

  // ── Ruins (Memory & Attention Mechanisms) ───────────────────────
  {
    id: 'memory-hall',
    name: 'Hall of Memory',
    emoji: '🏛️',
    aiConcept: 'Memory Cells',
    xp: 20,
    world: 'ruins',
    hint: 'The walls remember what the world has forgotten.',
  },
  {
    id: 'scroll-archive',
    name: 'Scroll Archive',
    emoji: '📜',
    aiConcept: 'Long-Term Memory',
    xp: 15,
    world: 'ruins',
  },
  {
    id: 'attention-pillar',
    name: 'Attention Pillar',
    emoji: '🔲',
    aiConcept: 'Attention Mechanism',
    xp: 25,
    world: 'ruins',
    hint: 'Some pillars glow brighter than others for a reason.',
  },
  {
    id: 'gate-mechanism',
    name: 'Gate Mechanism',
    emoji: '🚪',
    aiConcept: 'Gating',
    xp: 20,
    world: 'ruins',
    hidden: true,
  },
  {
    id: 'context-window',
    name: 'Context Window',
    emoji: '📕',
    aiConcept: 'Context Window',
    xp: 25,
    world: 'ruins',
  },
  {
    id: 'forgetting-stone',
    name: 'Forgetting Stone',
    emoji: '🪨',
    aiConcept: 'Forgetting Curve',
    xp: 20,
    world: 'ruins',
    hidden: true,
  },
  {
    id: 'recall-statue',
    name: 'Recall Statue',
    emoji: '📛',
    aiConcept: 'Recall & Precision',
    xp: 30,
    world: 'ruins',
  },

  // ── Sky (Generative AI & Creativity) ────────────────────────────
  {
    id: 'pattern-weave',
    name: 'Pattern Weave',
    emoji: '🌴',
    aiConcept: 'Pattern Generation',
    xp: 15,
    world: 'sky',
    hint: 'The clouds never repeat the same shape twice.',
  },
  {
    id: 'sampling-cloud',
    name: 'Sampling Cloud',
    emoji: '☁️',
    aiConcept: 'Sampling',
    xp: 15,
    world: 'sky',
  },
  {
    id: 'temperature-breeze',
    name: 'Temperature Breeze',
    emoji: '🍃',
    aiConcept: 'Temperature',
    xp: 20,
    world: 'sky',
    hint: 'A gentle breeze makes predictable shapes; a wild one makes art.',
  },
  {
    id: 'diffusion-mist',
    name: 'Diffusion Mist',
    emoji: '🌫️',
    aiConcept: 'Diffusion Models',
    xp: 25,
    world: 'sky',
    hidden: true,
  },
  {
    id: 'prompt-crystal',
    name: 'Prompt Crystal',
    emoji: '💎',
    aiConcept: 'Prompt Engineering',
    xp: 20,
    world: 'sky',
  },
  {
    id: 'latent-space',
    name: 'Latent Space',
    emoji: '🌌',
    aiConcept: 'Latent Space',
    xp: 30,
    world: 'sky',
    hidden: true,
  },
  {
    id: 'creative-peak',
    name: 'Creative Peak',
    emoji: '🌟',
    aiConcept: 'AI Creativity',
    xp: 30,
    world: 'sky',
  },
];

/** Look up a discovery by its id. */
export function getDiscoveryById(id: string): Discovery | undefined {
  return allDiscoveries.find((d) => d.id === id);
}
