// ternary-rom cell library: generic_90nm
// Generated by ROMCellLibrary
// Generic 90nm CMOS
// Cells: 20

module ROM_PLUS_X1_hvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X1, Vt: hvt
  // Size: 1.0 x 1.0 um, Leakage: 60.0 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X1_lvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X1, Vt: lvt
  // Size: 1.0 x 1.0 um, Leakage: 1200.0 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X1 (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X1, Vt: std
  // Size: 1.0 x 1.0 um, Leakage: 400.0 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X2_hvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X2, Vt: hvt
  // Size: 2.0 x 1.0 um, Leakage: 120.0 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X2_lvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X2, Vt: lvt
  // Size: 2.0 x 1.0 um, Leakage: 2400.0 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X2 (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X2, Vt: std
  // Size: 2.0 x 1.0 um, Leakage: 800.0 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_MINUS_X1_hvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X1, Vt: hvt
  // Size: 1.0 x 1.0 um, Leakage: 60.0 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X1_lvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X1, Vt: lvt
  // Size: 1.0 x 1.0 um, Leakage: 1200.0 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X1 (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X1, Vt: std
  // Size: 1.0 x 1.0 um, Leakage: 400.0 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X2_hvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X2, Vt: hvt
  // Size: 2.0 x 1.0 um, Leakage: 120.0 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X2_lvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X2, Vt: lvt
  // Size: 2.0 x 1.0 um, Leakage: 2400.0 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X2 (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X2, Vt: std
  // Size: 2.0 x 1.0 um, Leakage: 800.0 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_ZERO_X1_hvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X1, Vt: hvt
  // Size: 1.0 x 1.0 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X1_lvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X1, Vt: lvt
  // Size: 1.0 x 1.0 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X1 (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X1, Vt: std
  // Size: 1.0 x 1.0 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X2_hvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X2, Vt: hvt
  // Size: 2.0 x 1.0 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X2_lvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X2, Vt: lvt
  // Size: 2.0 x 1.0 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X2 (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X2, Vt: std
  // Size: 2.0 x 1.0 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_REF_HI (WL, BL);
  // ROM_REF_HI: always drives BL to VDD (reference high)
  // Drive: X1, Vt: std
  // Size: 1.0 x 1.0 um, Leakage: 400.0 pA
  input WL;
  output BL;

  assign BL = 1'b1;

endmodule

module ROM_REF_LO (WL, BL);
  // ROM_REF_LO: always drives BL to VSS (reference low)
  // Drive: X1, Vt: std
  // Size: 1.0 x 1.0 um, Leakage: 400.0 pA
  input WL;
  output BL;

  assign BL = 1'b0;

endmodule
