// ternary-rom cell library: gf14_lpp
// Generated by ROMCellLibrary
// GlobalFoundries 14nm LPP FinFET
// Cells: 29

module ROM_PLUS_X1_hvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X1, Vt: hvt
  // Size: 0.1 x 0.1 um, Leakage: 0.12 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X1_lvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X1, Vt: lvt
  // Size: 0.1 x 0.1 um, Leakage: 2.4 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X1 (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X1, Vt: std
  // Size: 0.1 x 0.1 um, Leakage: 0.8 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X2_hvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X2, Vt: hvt
  // Size: 0.2 x 0.1 um, Leakage: 0.24 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X2_lvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X2, Vt: lvt
  // Size: 0.2 x 0.1 um, Leakage: 4.8 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X2 (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X2, Vt: std
  // Size: 0.2 x 0.1 um, Leakage: 1.6 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X4_hvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X4, Vt: hvt
  // Size: 0.4 x 0.1 um, Leakage: 0.48 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X4_lvt (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X4, Vt: lvt
  // Size: 0.4 x 0.1 um, Leakage: 9.6 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_PLUS_X4 (WL, BL);
  // ROM_PLUS: when WL=1, drives BL to VDD (weight +1)
  // Drive: X4, Vt: std
  // Size: 0.4 x 0.1 um, Leakage: 3.2 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b1 : 1'bz;

endmodule

module ROM_MINUS_X1_hvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X1, Vt: hvt
  // Size: 0.1 x 0.1 um, Leakage: 0.12 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X1_lvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X1, Vt: lvt
  // Size: 0.1 x 0.1 um, Leakage: 2.4 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X1 (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X1, Vt: std
  // Size: 0.1 x 0.1 um, Leakage: 0.8 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X2_hvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X2, Vt: hvt
  // Size: 0.2 x 0.1 um, Leakage: 0.24 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X2_lvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X2, Vt: lvt
  // Size: 0.2 x 0.1 um, Leakage: 4.8 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X2 (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X2, Vt: std
  // Size: 0.2 x 0.1 um, Leakage: 1.6 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X4_hvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X4, Vt: hvt
  // Size: 0.4 x 0.1 um, Leakage: 0.48 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X4_lvt (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X4, Vt: lvt
  // Size: 0.4 x 0.1 um, Leakage: 9.6 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_MINUS_X4 (WL, BL);
  // ROM_MINUS: when WL=1, drives BL to VSS (weight -1)
  // Drive: X4, Vt: std
  // Size: 0.4 x 0.1 um, Leakage: 3.2 pA
  input WL;
  output BL;

  assign BL = WL ? 1'b0 : 1'bz;

endmodule

module ROM_ZERO_X1_hvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X1, Vt: hvt
  // Size: 0.1 x 0.1 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X1_lvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X1, Vt: lvt
  // Size: 0.1 x 0.1 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X1 (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X1, Vt: std
  // Size: 0.1 x 0.1 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X2_hvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X2, Vt: hvt
  // Size: 0.2 x 0.1 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X2_lvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X2, Vt: lvt
  // Size: 0.2 x 0.1 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X2 (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X2, Vt: std
  // Size: 0.2 x 0.1 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X4_hvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X4, Vt: hvt
  // Size: 0.4 x 0.1 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X4_lvt (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X4, Vt: lvt
  // Size: 0.4 x 0.1 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_ZERO_X4 (WL, BL);
  // ROM_ZERO: no transistors, BL left floating (weight 0)
  // Drive: X4, Vt: std
  // Size: 0.4 x 0.1 um, Leakage: 0.0 pA
  input WL;
  output BL;

  assign BL = 1'bz;

endmodule

module ROM_REF_HI (WL, BL);
  // ROM_REF_HI: always drives BL to VDD (reference high)
  // Drive: X1, Vt: std
  // Size: 0.1 x 0.1 um, Leakage: 0.8 pA
  input WL;
  output BL;

  assign BL = 1'b1;

endmodule

module ROM_REF_LO (WL, BL);
  // ROM_REF_LO: always drives BL to VSS (reference low)
  // Drive: X1, Vt: std
  // Size: 0.1 x 0.1 um, Leakage: 0.8 pA
  input WL;
  output BL;

  assign BL = 1'b0;

endmodule
